### ISSUE TITLE
No implementation found for method zipDirectory on channel flutter_archive

### ISSUE THREAD

**Issue by lucasjbyoung** [kineapps/flutter_archive#10]
Hi

I'm getting this error trying to use flutter-archive:

[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method zipDirectory on channel flutter_archive)

I've tried
flutter packages get
flutter packages upgrade
Run pod install in iOS folder

In my podfile I have:
platform :ios, '13.0'

in XCode 11.5 I set the deployment target to iOS 13

Anything I can try or is there any further debug info you need?

Cheers

**Comment by kinex** [comment]
Try also `flutter clean` and reinstalling the app in your device.

**Comment by lucasjbyoung** [comment]
No change unfortunately, running this on the simulator. Other Flutter plugins are working fine:

[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method zipDirectory on channel flutter_archive)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#2      ZipFile.createFromDirectory (package:flutter_archive/flutter_archive.dart:44:20)

**Comment by kinex** [comment]
So did you remove the app from simulator and then try again? From what I know this is a common issue in Flutter, see e.g. https://stackoverflow.com/questions/50687801/flutter-unhandled-exception-missingpluginexceptionno-implementation-found-for

**Comment by lucasjbyoung** [comment]
Yes, I've just tried:

Run 'flutter clean'
Run 'flutter pub get'
Delete the app from the emulator

Still the same problem. I can try creating a new Flutter app from scratch and using your example code just to see if it's my environment?

**Comment by kinex** [comment]
This was stupid issue from my side (my last minute change to pubspec.yaml broke the plugin). Sorry about this. Fixed in 1.0.1
