### ISSUE TITLE
java.util.zip.ZipException: No entries

### ISSUE THREAD

**Issue by gawkarhari** [kineapps/flutter_archive#11]
Getting Exception while creating zip in android using latest version and V0.1.4
Details Exception below
W/System.err(24617): java.util.zip.ZipException: No entries
W/System.err(24617): 	at java.util.zip.ZipOutputStream.finish(ZipOutputStream.java:363)
W/System.err(24617): 	at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:239)
W/System.err(24617): 	at java.util.zip.ZipOutputStream.close(ZipOutputStream.java:383)
W/System.err(24617): 	at kotlin.io.CloseableKt.closeFinally(Closeable.kt:53)
W/System.err(24617): 	at com.kineapps.flutterarchive.FlutterArchivePlugin.zip(FlutterArchivePlugin.kt:155)
W/System.err(24617): 	at com.kineapps.flutterarchive.FlutterArchivePlugin.access$zip(FlutterArchivePlugin.kt:32)
W/System.err(24617): 	at com.kineapps.flutterarchive.FlutterArchivePlugin$onMethodCall$1$1.invokeSuspend(FlutterArchivePlugin.kt:101)
W/System.err(24617): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err(24617): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
W/System.err(24617): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
W/System.err(24617): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
W/System.err(24617): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
W/System.err(24617): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)

**Comment by kinex** [comment]
This happens if you try to create a zip file from an empty directory (so there is nothing to zip). You can handle the error with try/catch. In my opinion this is working as intended.

**Comment by gawkarhari** [comment]
Thanks for reply @kinex but source destination has dir and in that there is a file is exist...we are giving valid source path too

**Comment by kinex** [comment]
Could you please provide a sample code to reproduce the issue.

**Comment by kinex** [comment]
Cannot reproduce.
