### ISSUE TITLE
Support for iOS before 10?

### ISSUE THREAD

**Issue by AAverin** [kineapps/flutter_archive#14]
Is there a reason why library only works from iOS 10 and higher?
Flutter supports starting iOS 8.

**Comment by kinex** [comment]
I think it should work also with older versions. Current limitation comes from my own projects. If I remember correctly, I had to set the same iOS version to all my packages or the build failed.

**Comment by AAverin** [comment]
Also failed for me and I set to iOS 10 for now.
Not critical for my project, but this limitation should be mentioned in the readme until it's resolved, could be a deal breaker for some and I only noticed it when I already built everything on Android and decided to test on iOS

**Comment by kinex** [comment]
Updated minimum version (iOS 10) to readme. If you need support for older versions, please make a PR. The used library ZIP Foundation requires iOS 9.0 or later, so I guess that is the absolute minimum version.

**Comment by kinex** [comment]
This was fixed in 2.0.1
