### ISSUE TITLE
on iOS progress doesn't reach 100%

### ISSUE THREAD

**Issue by AAverin** [kineapps/flutter_archive#15]
To make the library play nicely with futures, I am wrapping extraction with Completer
```
Future<bool> unpack() {
  final Completer<bool> result = Completer();
  ZipFile.extractToDirectory(
          zipFile: zipFile,
          destinationDir: destinationDir,
          onExtracting: (file, progress) {
            if (progress >= 100) {
              result.complete(true);
            }
            return ExtractOperation.extract;
          });
  return result.future;
}
```
Works great on Android, but completer never completes on iOS. In debug, I can see how extraction reaches >97%, but looks like it never hits 100.

What could be a better indication that process is finished?

**Comment by AAverin** [comment]
Ok, I just noticed that `extractToDirectory` returns a future.
Would just `await  ZipFile.extractToDirectory()` be enough?

**Comment by kinex** [comment]
Yes that should work.

**Comment by AAverin** [comment]
Confirming that it worked fine, my mistake.
Maybe would be a good point to show this in the sample?
