### ISSUE TITLE
the zipped file is the same size as the base file 

### ISSUE THREAD

**Issue by Abdaallaa** [kineapps/flutter_archive#16]
this is my example 
were the image came with imagePicker

`
                  String imageBaseName = path.basename(addImage.image.path);

                  String absoluteImageName = imageBaseName.substring(
                      0, imageBaseName.lastIndexOf("."));

                  String imageDirPath = addImage.image.path.substring(
                      0, addImage.image.path.length - imageBaseName.length);

                  Directory imageDir = Directory(imageDirPath);

                  File newZipFile = File(imageDir.path+"$absoluteImageName.zip");

                  final files = [addImage.image];

                  // for zipping 
                  try {
                         shit2.ZipFile.createFromFiles(
                         sourceDir: imageDir, files: files, zipFile: newZipFile);
                       } catch (e) {
                          print(e);
                       }  
`

**Comment by kinex** [comment]
JPEG images are already compressed, so zipping a JPEG files does not make it smaller.
