### ISSUE TITLE
压缩文件只有一个文件的时候，解压缩失败

### ISSUE THREAD

**Issue by changleibox** [kineapps/flutter_archive#18]
你好，在压缩文件只有一个文件的时候，解压缩失败，没有报错，但是目标目录没有文件，希望能得到你的帮助，谢谢

**Comment by kinex** [comment]
I cannot reproduce the issue with the example app. Please provide code to reproduce the issue.

**Comment by kinex** [comment]
Please reopen if you can provide a code sample to reproduce the issue.
