### ISSUE TITLE
Charset problem

### ISSUE THREAD

**Issue by ZXQ-Kyle** [kineapps/flutter_archive#25]
I have got a problem of charset, when my zipfile contain a file with Gbk charset which compressed on windows，i will unzip failed，but when i change 
`    class ZipFileEx(name: String?) : ZipFile(File(name), ZipFile.OPEN_READ, Charset.forName("GBK")), Closeable
`
this problem will solved，but this constructor  requires API level 24，will you have any plan to resolve this problem

**Comment by kinex** [comment]
Please make a PR if you need this soon. I think we cannot change minimum required API level, so you should check system version at runtime.
https://developer.android.com/training/basics/supporting-devices/platforms

**Comment by kinex** [comment]
I was able to reproduce this issue by creating a zip file with the app 7-Zip (Windows). One of the file names in the zip contained "ö" and "ä". Trying to unzip this file using this plugin resulted exception "MALFORMED".
