### ISSUE TITLE
mac version not working due to regular file instead of symlink

### ISSUE THREAD

**Issue by fibbers** [kineapps/flutter_archive#26]
First of all, thanks for providing this library 👍 

I'm trying to build a Mac desktop app and when Flutter runs `pub get`, I see the following:
(stripping prefix dir `/opt/flutter/.pub-cache/hosted/pub.dartlang.org/`)
```sh
$ ls -l flutter_archive-2.0.1/macos/Classes/SwiftFlutterArchivePlugin.swift
-rwxr-xr-x  1 willem  wheel    49B Dec 15 13:03 /flutter_archive-2.0.1/macos/Classes/SwiftFlutterArchivePlugin.swift
$ cat /flutter_archive-2.0.1/macos/Classes/SwiftFlutterArchivePlugin.swift
../../ios/Classes/SwiftFlutterArchivePlugin.swift
```
and this triggers a Swift error `Expressions are not allowed at the top level` since it's a regular file instead of a symlink.

When I remove the file and actually create a symlink towards that path, it works:
```sh
$ rm /flutter_archive-2.0.1/macos/Classes/SwiftFlutterArchivePlugin.swift
$ ln -s ../../ios/Classes/SwiftFlutterArchivePlugin.swift /flutter_archive-2.0.1/macos/Classes/SwiftFlutterArchivePlugin.swift
$ ls -l /flutter_archive-2.0.1/macos/Classes/SwiftFlutterArchivePlugin.swift
lrwxr-xr-x  1 willem  wheel  49 Jan 28 21:06 /flutter_archive-2.0.1/macos/Classes/SwiftFlutterArchivePlugin.swift -> ../../ios/Classes/SwiftFlutterArchivePlugin.swift
```
now my app starts running.

---

I tried to create a PR by making the file a symlink, but I saw [it already is a symlink](https://github.com/kineapps/flutter_archive/blob/1eb9bedaeb4cb5aaaee083770d9d09add40aadc1/macos/Classes/SwiftFlutterArchivePlugin.swift).

So maybe `pub` doesn't work too well with symlinks, either during publishing or during downloading 🤷‍♂️ 
I did find [this issue](https://github.com/dart-lang/pub/pull/2827), which might be related.

NB: my `flutter --version` is:
```sh
Flutter 1.26.0-12.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision a706cd2112 (2 weeks ago) • 2021-01-14 18:20:26 -0500
Engine • revision effb529ece
Tools • Dart 2.12.0 (build 2.12.0-224.0.dev)
```

**Comment by kinex** [comment]
Thanks for your issue report. Please suggest how to fix this, or make a PR. I am not building for Mac in my own projects currently (Mac support was implemented by a contributor). I could look at this later when I have time.

**Comment by fibbers** [comment]
I'm not sure what's the best solution, but could it be that you're doing `pub publish` from a Windows machine which might process symlinks incorrectly (just a guess 🤷)? In that case doing `pub publish` from Linux/Mac might fix it, if that's a feasible option.

And otherwise, I can make a simple PR which removes the symlink and just uses a copy of the file. Downside of course is that maintenance now has to be done in 2 places.

Let me know, I'm happy to create a PR with just a copy of the involved file.

**Comment by fibbers** [comment]
I created a PR anyway, just in case the Linux/Mac suggestion might not be a solution.

Either decline the PR or merge it, I'm fine with both 😄

**Comment by kinex** [comment]
Could you please check if 2.0.2 fixes this. I published the plugin from Mac.

**Comment by fibbers** [comment]
Just updated to 2.0.2 and now it works out of the box 👍  I'll close my PR.
Thanks!

**Comment by kinex** [comment]
Great! Thanks for your help.
