### ISSUE TITLE
Add ability to stop zip/unzip

### ISSUE THREAD

**Issue by m7mdra** [kineapps/flutter_archive#27]
My usecase is that i have a large zip file containing a 300mb database that might take alot of time to extract and not all user will wait until its finished. 

so i was wondering if its possible to cancle/stop process?

**Comment by kinex** [comment]
You can cancel it by returning `ExtractOperation.cancel` from the `onExtracting` callback.

**Comment by m7mdra** [comment]
Thanks for the following up. i will give it a try, although i think it's very inconvenient way to cancel a process. thanks again.
