### ISSUE TITLE
Uncompressing in ios takes way longer in comparison with android

### ISSUE THREAD

**Issue by m7mdra** [kineapps/flutter_archive#31]
i noticed that using simulator/ real phone (iphone7s) that uncompressing take longer than android, at first i thought it might be related to simulator being limited in resources but when i ran it in real phone i noticed the same behavior applies.

thanks in advance.

**Comment by kinex** [comment]
Why do you think this is an issue in this plugin, was it extremely slow? Different devices have different CPUs etc, so uncompressing times will be always different.

Also, please use a release build to make any benchmark tests. Benchmarks using a debug build are meaningless.

**Comment by m7mdra** [comment]
It was extremely slow but maybe it because it was a debug build.

will close this for now , and will try with release build.
