### ISSUE TITLE
PlatformException (PlatformException(unzip_error, MALFORMED[1], java.lang.IllegalArgumentException: MALFORMED[1], null))

### ISSUE THREAD

**Issue by bhtri** [kineapps/flutter_archive#32]
Hi everyone!
I tried extracting the zip file that has the following structure
```
image
  >本田
    > img1.png
    > img2.png
  >山田
    >img1.jpg
    >img2.jpg
  >無題名.xlsx
```
then get the following Exception on Android
```
PlatformException (PlatformException(unzip_error, MALFORMED[1], java.lang.IllegalArgumentException: MALFORMED[1], null))
```
on iOS it can still unzip but the directory/ file name cannot be read (Garbled characters).
Thanks for all comments and sharing!

**Comment by kinex** [comment]
Maybe related to #25?
