### ISSUE TITLE
Created ZIP is not supported on macbook

### ISSUE THREAD

**Issue by ABHISHEK-360** [kineapps/flutter_archive#35]
MacOs archive utility is unable to expand with error "unsupported format"
[abcd.zip](https://github.com/kineapps/flutter_archive/files/6680802/abcd.zip)

**Comment by kinex** [comment]
It looks like some other app has modified the file by adding there some header data. If you remove the header (use a text editor), the zip can be opened normally. So I don't think the issue is related to this plugin.
