### ISSUE TITLE
 Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors

### ISSUE THREAD

**Issue by dim0147** [kineapps/flutter_archive#42]
- Hi, I install the package and re-install the app and turn to this error:
![image](https://user-images.githubusercontent.com/44487221/139567306-d37db091-f439-4159-91e2-afa21251e173.png)

**Comment by 47krishnaveersingh** [comment]
> * Hi, I install the package and re-install the app and turn to this error:
>   ![image](https://user-images.githubusercontent.com/44487221/139567306-d37db091-f439-4159-91e2-afa21251e173.png)

**Did you find the answer?**

**Comment by dim0147** [comment]
> > * Hi, I install the package and re-install the app and turn to this error:
> >   ![image](https://user-images.githubusercontent.com/44487221/139567306-d37db091-f439-4159-91e2-afa21251e173.png)
> 
> **Did you find the answer?**

Yes, in my case it help, you can see here:
https://stackoverflow.com/a/69369027/9611273
