### ISSUE TITLE
Update ZIPFoundation

### ISSUE THREAD

**Issue by jakub-cosmose** [kineapps/flutter_archive#48]
The project depends on ZIPFoundation 0.9.11, which has been releases nearly 2 years ago. Can we update it to the latest version, e.g. for better handling of large files (added in 0.9.13)?

**Comment by daniel-possienke** [comment]
I've already added a PR for this (see [here](https://github.com/kineapps/flutter_archive/pull/47)). I'm just waiting for @kinex  to approve that PR.
