### ISSUE TITLE
I have gotten this error when try to excuse pod install

### ISSUE THREAD

**Issue by islam-Ellithy** [kineapps/flutter_archive#5]
I have gotten this error when try to excuse pod install

[!] CocoaPods could not find compatible versions for pod "flutter_archive":
  In Podfile:
    flutter_archive (from `.symlinks/plugins/flutter_archive/ios`)

Specs satisfying the `flutter_archive (from `.symlinks/plugins/flutter_archive/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by wcyDreamer** [comment]
> I have gotten this error when try to excuse pod install
> 
> [!] CocoaPods could not find compatible versions for pod "flutter_archive":
> In Podfile:
> flutter_archive (from `.symlinks/plugins/flutter_archive/ios`)
> 
> Specs satisfying the `flutter_archive (from `.symlinks/plugins/flutter_archive/ios`)` dependency were found, but they required a higher minimum deployment target.

did you solve this problem? i also meet this problem when i pod install.

**Comment by kinex** [comment]
Deployment target of this plugin has been set to 10.0 (mainly due to requirements in my own apps). It may work also with older versions. To try this you should clone this repo and update this line in the file `flutter_archive.podspec` :
`s.ios.deployment_target = '10.0'`

**Comment by islam-Ellithy** [comment]
> > I have gotten this error when try to excuse pod install
> > [!] CocoaPods could not find compatible versions for pod "flutter_archive":
> > In Podfile:
> > flutter_archive (from `.symlinks/plugins/flutter_archive/ios`)
> > Specs satisfying the `flutter_archive (from `.symlinks/plugins/flutter_archive/ios`)` dependency were found, but they required a higher minimum deployment target.
> 
> did you solve this problem? i also meet this problem when i pod install.

yes in ios->Podfile 
add that at the beginning of the file
platform :ios, '10.0'

**Comment by kinex** [comment]
Please reopen if still occurs

**Comment by PiN73** [comment]
Should be solved by https://github.com/kineapps/flutter_archive/pull/22
