### ISSUE TITLE
flutter_archive.dart error

### ISSUE THREAD

**Issue by CGuoJunLi** [kineapps/flutter_archive#51]
/[D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_archive-4.2.0/lib/flutter_archive.dart:196:46](): Error: The getter 'name' isn't defined for the class 'ZipFileOperation'.
- 'ZipFileOperation' is from 'package:flutter_archive/flutter_archive.dart' ('/[D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_archive-4.2.0/lib/flutter_archive.dart]()').
package:flutter_archive/flutter_archive.dart:1
Try correcting the name to the name of an existing getter, or defining a getter or field named 'name'.
          return Future<String>.value(result.name);

**Comment by kinex** [comment]
Thanks for the bug report. Should be fixed by https://github.com/kineapps/flutter_archive/commit/3fbc307a84bc7e4a863911ecd693bc5da7ba1d95 . You must upgrade Flutter to a newer version.
