### ISSUE TITLE
zipping a directory doesn't include the root directory

### ISSUE THREAD

**Issue by sgehrman** [kineapps/flutter_archive#6]
I zip a directory, then unzip it I don't get back the original folder, I just get the contents scattered all over the destination directory rather than in it's original directory.

With 'archive' I can do this with includeDirName: true, but 'archive' is buggy and doesn't handle symlinks correctly.

**Comment by kinex** [comment]
Fix is available in master. Updated plugin will be published later.

**Comment by kinex** [comment]
Fixed in 1.0.0
