### ISSUE TITLE
Fails to build on Android with Flutter 3.7.0.

### ISSUE THREAD

**Issue by mtjaffacode** [kineapps/flutter_archive#68]
Latest Flutter requires you to have a later version of gradle.

* What went wrong:
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_archive' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.30

**Comment by kinex** [comment]
Fixed in 6.0.0
