### ISSUE TITLE
No implementation found for method unzip on channel flutter_archive

### ISSUE THREAD

**Issue by adiospace** [kineapps/flutter_archive#9]
So, I just updated to 1.0.0 and I get this error when unzipping on ios.

`flutter: error downloading MissingPluginException(No implementation found for method unzip on channel flutter_archive)`

I'm not sure, but it seems the pod is not installed correctly if at all.

I tried flutter clean, rm -rf Pods and rm -rf Podfile.lock without any luck and I'm also using `platform :ios, '10.0'` on Podfile.

Any ideas?

**Comment by kinex** [comment]
Please try one/all of these:
`flutter packages get` 
`flutter packages upgrade`
Run `pod install` in iOS folder

**Comment by kinex** [comment]
Found the issue, fixed in 1.0.1
